{% set name = "tree" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://oldmanprogrammer.net/tar/tree/{{ name }}-{{ version }}.tgz
  sha256: 208cdf8d76b308cece6e77f47c92daebce093d1470dec4a2d6dd77aa6f656886

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - test -f ${PREFIX}/bin/tree
    - tree --version

about:
  home: http://oldmanprogrammer.net/source.php?dir=projects/tree
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Tree is a recursive directory listing command
  description: |
    "Tree is a recursive directory listing command that produces a depth
    indented listing of files, which is colorized ala dircolors if the
    LS_COLORS environment variable is set and output is to tty. Tree has been
    ported and reported to work under the following operating systems: Linux,
    FreeBSD, OS X, Solaris, HP/UX, Cygwin, HP Nonstop and OS/2."
  doc_url: http://oldmanprogrammer.net/source.php?dir=projects/tree
  dev_url: https://gitlab.com/OldManProgrammer/unix-tree

extra:
  recipe-maintainers:
    - moorepants
