{% set name = "tree" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://mama.indstate.edu/users/ice/tree/src/{{ name }}-{{ version }}.tgz
  sha256: b0ea92197849579a3f09a50dbefc3d4708caf555d304a830e16e20b73b4ffa74
  patches:
    - Makefile.linux.patch  # [linux]
    - Makefile.osx.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/bin/tree
    - tree --version

about:
  home: http://mama.indstate.edu/users/ice/tree/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Tree is a recursive directory listing command
  description: |
    Tree is a recursive directory listing command that produces a depth
    indented listing of files, which is colorized ala dircolors if the
    LS_COLORS environment variable is set and output is to tty. Tree has been
    ported and reported to work under the following operating systems: Linux,
    FreeBSD, OS X, Solaris, HP/UX, Cygwin, HP Nonstop and OS/2.
  doc_url: http://mama.indstate.edu/users/ice/tree/tree.1.html

extra:
  recipe-maintainers:
    - moorepants
